name: hisaab

services:
  hisaab:
    build: .
    container_name: hisaab
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ${DATA_LOCATION:-./data}:/app/data
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
